### ISSUE TITLE
Individual post page is not responsive 

### ISSUE THREAD

**Issue by binbard** [narayan954/dummygram#378]
### Description

The individual post page is not responsive for mobile devices, causing poor user experience. Even it is completely hidden for most of the mobile devices.

### Steps to reproduce

1. Click on the title of any post (author name)
2. The post should have be opened individually
3. Note that this page is not responsive

### Screenshots

https://github.com/narayan954/dummygram/assets/28684962/c84d7c59-4f4d-4a74-afcb-c38098b84e14

### Smartphone (please complete the following information)

Mobile devices (width <1200px)

### Additional information

Please **_assign to me_** under GSSOC'23

---
### TODO:
- [x] Modify HTML structure to support responsive design.
- [x] Update CSS styles for the individual post page.
- [x] Test the changes on multiple mobile devices and browsers.

**Comment by binbard** [comment]
Please assign to it me

**Comment by narayan954** [comment]
Hi @binbard, thanks a lot for raising the issue! feel free to work on this!
